<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <body bgcolor=black>
    <table width=100% height=100%>
      <td align=center><br><br><br><br><br><br><br><br>
        <link href='http://fonts.googleapis.com/css?family=Orbitron:700' rel='stylesheet' type='text/css'>
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
      <title>h4cked by Ixp666Sec</title>
      </script>

      <link rel="icon" href="https://i.ibb.co/86bK7d6/20230908-061411.jpg">
      <style media="screen">

        <body oncontextmenu='return false;' onkeydown='return false;' onmousedown='return false;'>
        <style type="text/css">
        h1 {
          color: #333;
          font-size: 50px;
          margin: 0px auto;
          text-align: center;
          text-transform: uppercase;
          font-family: Orbitron;
        }
        .neon {
          color: #FFFFFF;
          text-shadow: 0 0 5px #FF0000, 0 0 10px#FF0000, 0 0 30px #FF0000, 0 0 45px #FF0000, 0 0 60px #FF0000;
        }

        .matrix {
          color: #FFFFFF;
          font-family: Arial, Courier, Monotype;
          font-size: 15pt;
          text-align: center;
          width: 10px;
          padding: 0px;
          margin: 0px;
        }
        .jokitz1 {
          text-align: center;
        }
        .jokitz2 {
          text-align: center;
          font-family: Courier;
        }
      </style>
      <script type="text/javascript">

        <!--

        var message = "Ooooooppppssssss....! Sorry";

        ///////////////////////////////////

        function clickIE() {
          if (document.all) {(message); return false;
          }}

        function clickNS(e) {
          if

            (document.layers || (document.getElementById&&!document.all)) {

            if (e.which == 2 || e.which == 3) {(message); return false;
            }}}

        if (document.layers) {
          document.captureEvents(Event.MOUSEDOWN); document.onmousedown = clickNS;
        } else {
          document.onmouseup = clickNS; document.oncontextmenu = clickIE;
        }

        document.oncontextmenu = new Function("return false")

        // -->

      </script>

      <script type="text/javascript" language="javascript">


        <!--

        var rows = 1; // must be an odd number

        var speed = 10; // lower is faster

        var reveal = 2; // between 0 and 2 only. The higher, the faster the word appears

        var effectalign = "center" //enter "center" to center it.

        var w3c = document.getElementById && !window.opera;;

        var ie45 = document.all && !window.opera;

        var ma_tab, matemp, ma_bod, ma_row, x, y, columns, ma_txt, ma_cho;

        var m_coch = new Array();

        var m_copo = new Array();

        window.onload = function() {

          if (!w3c && !ie45) return

          var matrix = (w3c)?document.getElementById("matrix"): document.all["matrix"];

          ma_txt = (w3c)?matrix.firstChild.nodeValue: matrix.innerHTML;

          ma_txt = " "+ma_txt+" ";

          columns = ma_txt.length;

          if (w3c) {

            while (matrix.childNodes.length) matrix.removeChild(matrix.childNodes[0]);

            ma_tab = document.createElement("table");

            ma_tab.setAttribute("border", 0);

            ma_tab.setAttribute("align", effectalign);

            ma_tab.style.backgroundColor = "#000000";

            ma_bod = document.createElement("tbody");

            for (x = 0; x < rows; x++) {

              ma_row = document.createElement("tr");

              for (y = 0; y < columns; y++) {

                matemp = document.createElement("td");

                matemp.setAttribute("id", "Mx"+x+"y"+y);

                matemp.className = "matrix";

                matemp.appendChild(document.createTextNode(String.fromCharCode(160)));

                ma_row.appendChild(matemp);

              }

              ma_bod.appendChild(ma_row);

            }

            ma_tab.appendChild(ma_bod);

            matrix.appendChild(ma_tab);

          } else {

            ma_tab = '<ta'+'ble align="'+effectalign+'" border="0" style="background-color:#000000">';

            for (var x = 0; x < rows; x++) {

              ma_tab += '<t'+'r>';

              for (var y = 0; y < columns; y++) {

                ma_tab += '<t'+'d class="matrix" id="Mx'+x+'y'+y+'"> </'+'td>';

              }

              ma_tab += '</'+'tr>';

            }

            ma_tab += '</'+'table>';

            matrix.innerHTML = ma_tab;

          }

          ma_cho = ma_txt;

          for (x = 0; x < columns; x++) {

            ma_cho += String.fromCharCode(32+Math.floor(Math.random()*94));

            m_copo[x] = 0;

          }

          ma_bod = setInterval("mytricks()", speed);

        }



        function mytricks() {

          x = 0;

          for (y = 0; y < columns; y++) {

            x = x+(m_copo[y] == 100);

            ma_row = m_copo[y]%100;

            if (ma_row && m_copo[y] < 100) {

              if (ma_row < rows+1) {

                if (w3c) {

                  matemp = document.getElementById("Mx"+(ma_row-1)+"y"+y);

                  matemp.firstChild.nodeValue = m_coch[y];

                } else {

                  matemp = document.all["Mx"+(ma_row-1)+"y"+y];

                  matemp.innerHTML = m_coch[y];

                }

                matemp.style.color = "#FF0000";

                matemp.style.fontWeight = "bold";

              }

              if (ma_row > 1 && ma_row < rows+2) {

                matemp = (w3c)?document.getElementById("Mx"+(ma_row-2)+"y"+y): document.all["Mx"+(ma_row-2)+"y"+y];

                matemp.style.fontWeight = "normal";

                matemp.style.color = "#FF0000";

              }

              if (ma_row > 2) {

                matemp = (w3c)?document.getElementById("Mx"+(ma_row-3)+"y"+y): document.all["Mx"+(ma_row-3)+"y"+y];

                matemp.style.color = "#FF0000";

              }

              if (ma_row < Math.floor(rows/2)+1) m_copo[y]++;

              else if (ma_row == Math.floor(rows/2)+1 && m_coch[y] == ma_txt.charAt(y)) zoomer(y);

              else if (ma_row < rows+2) m_copo[y]++;

              else if (m_copo[y] < 100) m_copo[y] = 0;

            } else if (Math.random() > 0.9 && m_copo[y] < 100) {

              m_coch[y] = ma_cho.charAt(Math.floor(Math.random()*ma_cho.length));

              m_copo[y]++;

            }

          }

          if (x == columns) clearInterval(ma_bod);

        }



        function zoomer(ycol) {

          var mtmp,
          mtem,
          ytmp;

          if (m_copo[ycol] == Math.floor(rows/2)+1) {

            for (ytmp = 0; ytmp < rows; ytmp++) {

              if (w3c) {

                mtmp = document.getElementById("Mx"+ytmp+"y"+ycol);

                mtmp.firstChild.nodeValue = m_coch[ycol];

              } else {

                mtmp = document.all["Mx"+ytmp+"y"+ycol];

                mtmp.innerHTML = m_coch[ycol];

              }

              mtmp.style.color = "#FF0000";

              mtmp.style.fontWeight = "bold";

            }

            if (Math.random() < reveal) {

              mtmp = ma_cho.indexOf(ma_txt.charAt(ycol));

              ma_cho = ma_cho.substring(0, mtmp)+ma_cho.substring(mtmp+1, ma_cho.length);

            }

            if (Math.random() < reveal-1) ma_cho = ma_cho.substring(0, ma_cho.length-1);

            m_copo[ycol] += 199;

            setTimeout("zoomer("+ycol+")", speed);

          } else if (m_copo[ycol] > 200) {

            if (w3c) {

              mtmp = document.getElementById("Mx"+(m_copo[ycol]-201)+"y"+ycol);

              mtem = document.getElementById("Mx"+(200+rows-m_copo[ycol]--)+"y"+ycol);

            } else {

              mtmp = document.all["Mx"+(m_copo[ycol]-201)+"y"+ycol];

              mtem = document.all["Mx"+(200+rows-m_copo[ycol]--)+"y"+ycol];

            }

            mtmp.style.fontWeight = "normal";

            mtem.style.fontWeight = "normal";

            setTimeout("zoomer("+ycol+")", speed);

          } else if (m_copo[ycol] == 200) m_copo[ycol] = 100+Math.floor(rows/2);

          if (m_copo[ycol] > 100 && m_copo[ycol] < 200) {

            if (w3c) {

              mtmp = document.getElementById("Mx"+(m_copo[ycol]-101)+"y"+ycol);

              mtmp.firstChild.nodeValue = String.fromCharCode(160);

              mtem = document.getElementById("Mx"+(100+rows-m_copo[ycol]--)+"y"+ycol);

              mtem.firstChild.nodeValue = String.fromCharCode(160);

            } else {

              mtmp = document.all["Mx"+(m_copo[ycol]-101)+"y"+ycol];

              mtmp.innerHTML = String.fromCharCode(160);

              mtem = document.all["Mx"+(100+rows-m_copo[ycol]--)+"y"+ycol];

              mtem.innerHTML = String.fromCharCode(160);

            }

            setTimeout("zoomer("+ycol+")", speed);

          }



          //start

          var h1 = document.getElementsByTagName("h1")[0],

          text = h1.innerText || h1.textContent,

          split = [],
          i,
          lit = 0,
          timer = null;

          for (i = 0; i < text.length; ++i) {

            split.push("<span>" + text[i] + "</span>");

          }

          h1.innerHTML = split.join("");

          split = h1.childNodes;



          var flicker = function() {

            lit += 0.01;

            if (lit >= 1) {

              clearInterval(timer);

            }

            for (i = 0; i < split.length; ++i) {

              if (Math.random() < lit) {

                split[i].className = "neon";

              } else {

                split[i].className = "";

              }

            }

          }

          setInterval(flicker, 100);


        }


      </script>
    </head>

    <p>
    	 <script>alert("HACKED BY Ixp666");</script>
         <script>alert("FREE MUSLIM !!");</script>
      <img src="https://i.ibb.co/86bK7d6/20230908-061411.jpg"style="width:450px;height:450px;" align="top">
    </p>
    <center>
    <br><br>  <h1> HACKED_BY_IXP666SEC </h1>

      <div id="matrix" class="auto-style8">
        You're Website Not Safe
      </div>
      <br>

      <font face="Lucida Console" color="white" size="6px">
          
 [ Ixp666Sec ]<br><br>Pity the website is broken<br>WARM GREETINGS IXP666SECTEAM<br><br>Fuck india. stop oppressing muslims<br>We Indonesian hackers will not stoped destroyed your website<br>	 </font></b>

    </style>
    <br />
  <script type="text/javascript">
    var charIndex = -1;
    var stringLength = 0;
    var inputText;
    function writeContent(init) {
      if (init) {
        inputText = document.getElementById('contentToWrite').innerHTML;
      }
      if (charIndex==-1) {
        charIndex = 0;
        stringLength = inputText.length;
      }
      var initString = document.getElementById('myContent').innerHTML;
      initString = initString.replace(/<SPAN.*$/gi, "");

      var theChar = inputText.charAt(charIndex);
      var nextFourChars = inputText.substr(charIndex, 4);
      if (nextFourChars == '<br>' || nextFourChars == '<br>') {
        theChar = '<br>';
        charIndex += 3;
      }
      initString = initString + theChar + "<span id='blink'>_</SPAN>";
      document.getElementById('myContent').innerHTML = initString;

      charIndex = charIndex/1 +1;
      if (charIndex%2 == 1) {
        document.getElementById('blink').style.display = 'font: 100px';
      } else {
        document.getElementById('blink').style.display = 'inline';
      }

      if (charIndex <= stringLength) {
        setTimeout('writeContent(false)', 100);
      } else {
        blinkSpan();
      }
    }
    var currentStyle = 'inline';
    function blinkSpan() {
      if (currentStyle == 'inline') {
        currentStyle = 'none';
      } else {
        currentStyle = 'inline';
      }
      document.getElementById('blink').style.display = currentStyle;
      setTimeout('blinkSpan()', 9999999);

    }
  </script>
</html>
</embed>


  <body>
  </style>
  <h1>
    <center>
      <font color="green">
     -  | /XizB3f | Sanzx | RizkulSec | LUCAS X PLOIT | AnggaXploit | /Fakesec666 | ixp666Sec | ./Stormxploit | U.E | RED GHOST | GrenXparta | MrKaktus/AstroBOY | Suapnasi01 | Wira-Coding Failed | Black Devil | sudo.exploit | br4ns | n0 N4m391 | /USERVXII | MrVxdx1-Xploit  | Mrx.az.al | davsec | SLX_94 | Mr.A | LetnanCurut | ./iEthesia | ToKyO | /TnPandaXploit- All My Friends
      </marquee></font></b>
</div>
</span>
<center>

</script>
</html>
</embed>

</html>
<font face="trade Winds" size="4">
<marquee direction="right" scrollamount="6" width="80%" style="width: 80%;">
<body>
</style>
<h1>
<center>
<font color="white">
<br><br> | HIZBULLAH CYB3R TEAM| HACKTIVITS INDONESIA | GANOSEC | FR3DENS OF SECURITY  | GARUDA SECURITY | AERONIX O7 | CIPINANG BL4CKHAT | Silent Devil Team | INFECTSEC TEAM |  HakunaSec | PANOC TEAM | JAMBI CYBER TEAM | WARLOCK DARK ARMY | Lulz Security Agency | KETAPANG GREYHAT| GARNESIA-ID | ATTACKER TO CYBER | THE UCHIHA CLAN </p>>
</marquee></font></b>
</div>
</span>
<center>

<input type="radio" name="person" value="©copyright" id="©copyright" />
<label for="©copyright"><span></span>
<audio autoplay>

<source src="https://kosred.com/a/bqumej.mp3" type="audio/mp3">
</audio>
</div>
<br>
<font size="1">
<p>
<audio src="https://kosred.com/a/bqumej.mp3" autoplay controls></audio>
</p>
<div class="footer-greetings">
<audio autoplay>
</audio>
</td>
</font>

<br>

</head>

<link href="https://fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">



<body bgcolor="white">

<table width="10%" height="1000%">

<td align="center">



<style type="text/css">

.x {

font-size: 15px;

transform: skewY(-8deg);

}

</style>


<font color="black" face="Space Mono">

<h1> class="x"><font color="red"> Touch by: Ixp666Sec
</h1>
<font color="black"> 